name: Go Test
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  test:
    name: "go test"
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x, 1.18.x, 1.19.x, 1.20.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: gormer
          MYSQL_ROOT_PASSWORD: "123456"
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -p123456"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: ./go.sum
      - run: go version

      - name: Run tests
        run: go test ./... -v -covermode=atomic -race -coverprofile=coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3